### PR TITLE
build.sh removes Modules folder

### PR DESCRIPTION
**Pull request by Powerz**
build.sh should not remove the whole Modules folder because it may contain the packages.config file.

### CODE REVIEW

**Comment by gep13** [comment]
@Powerz thank you for taking the time to submit this Pull Request, however, I am not sure if this is the correct approach.

The way that the current Bootstrappers work is that they will trigger off a modification of the main packages.config file.  If anything in there changes, the contents of the tools folder will be removed, and then replaced.  The problem here is that the packages.config file in the Modules folder is also being removed (and this is also true of the packages.config file in the Addins folder if one exists).  This technique was necessary due to the way that Cake used to process NuGet packages.  With the 0.25.0 release of Cake, this technique will no longer be required, and as such, I don't think this solution will be required.  If we were to move this in temporarily, I think the better approach would be to remove everything the Modules folder, with the exception of the packages.config file.

Regardlass of the above, if we were to continue down this route, we would need to make the same change to the PowerShell bootstrapper so that they are consistent.

**Comment by Powerz** [comment]
Hi @gep13 ,

Thank you for the review and feedback. I have updated the Powershell bootstrapper and added the Addins folder.

All subfolders of Modules and Addins are going to be removed, but not files, so package.config-s should survive. That should be enough I suppose.

Please review the PR at your convenience.

**Comment by ltrzesniewski** [comment]
@gep13 I just experienced this issue on 0.30.0, but your message suggests this PR shouldn't be necessary for 0.25.0+. Looks like it still is.

**Comment by pascalberger** [comment]
We did some maintenance work on this repo which included removing of the `develop` branch which closed this PR.

@Powerz If this is still an issue please create a new PR targeting the `master` branch

**Pull request closed without merging**
