### PR TITLE
Handle empty strings in PATH

### PR DESCRIPTION
**Pull request by gep13**
Relates to #2

### CODE REVIEW

**Comment by gep13** [comment]
@patriksvensson also this one :smile:

**Comment by patriksvensson** [comment]
@gep13 Is this tested?

**Comment by gep13** [comment]
@patriksvensson no, I haven't tested this.  I simply duplicated the existing PR while I was closing it out :smile:

**Comment by patriksvensson** [comment]
@gep13 Ok, I'll take it for a spin then.

**Pull request merged**
