### PR TITLE
Create TeamCity Metarunner for Bootstrapper

### PR DESCRIPTION
**Pull request by DTTerastar**
I'm not sure exactly where this should go, but an official TeamCity metarunner would definitely help the community.  This is built to exactly use the boostrapper.ps1 unmodified.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/cake-build/resources?pullRequest=86) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/cake-build/resources?pullRequest=86) before we can accept your contribution.<br/><br/>:x: DTTerastar [sign now](https://cla.dotnetfoundation.org/cake-build/resources?pullRequest=86)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/cake-build/resources?pullRequest=86) it.</sub>

**Comment by pascalberger** [comment]
@DTTerastar Thanks for the pull request 👍  

While not much happened recently, we already have a TeamCity meta-runner in this repository: https://github.com/cake-build/cake-teamcity. Can you please have a look at this and if you have improvements make a PR there.

Documentation on website is currently missing. But we would like to add it there too (this is https://github.com/cake-build/website/issues/1047).

**Review by pascalberger — CHANGES_REQUESTED** [review]
@DTTerastar Thanks for the pull request 👍  

While not much happened recently, we already have a TeamCity meta-runner in this repository: https://github.com/cake-build/cake-teamcity. Can you please have a look at this and if you have improvements make a PR there.

Documentation on website is currently missing. But we would like to add it there too (this is https://github.com/cake-build/website/issues/1047).

**Comment by pascalberger** [comment]
Another point: While historically there was just a single runner for Cake (cake.exe built on top of .NET Framework) existed, since quite some time there are different runners (see https://cakebuild.net/docs/running-builds/runners/). While we currently still support Cake runner for .NET Framework, going forward we will recommend to use [.NET Tool](https://cakebuild.net/docs/running-builds/runners/dotnet-core-tool). 

I'm more than happy to give the meta runner at https://github.com/cake-build/cake-teamcity some love to bring it up to date for current .NET Framework runner and also make it more visible by addin to website. In the future demand probably might be more for a .NET Tool version.

**Comment by pascalberger** [comment]
We did some maintenance work on this repo which included removing of the develop branch which closed this PR. 

@DTTerastar Are you still interested in updating the TeamCity meta-runner. In this case please create a new PR in the https://github.com/cake-build/cake-teamcity repo.

**Pull request closed without merging**
