### PR TITLE
Add stubs for new bootstrappers

### PR DESCRIPTION
**Pull request by gep13**
This will allow hooking up of the Cake extension for Visual Studio Code
to use these.  Actual implementation will come once everything is hooked
up.

### CODE REVIEW

**Review by pascalberger — COMMENTED** [review]
I would call the folder `dotnettool` instead of the soon to be deprecated term `.NET Core Tool`, since there won't be any .NET Core going forward. On nuget.org for example they are already called `.NET Tool`.

Another point: We don't move the existing bootstrappers into a sub directory to not break stuff?

**Comment by gep13** [comment]
>@pascalberger said...
Another point: We don't move the existing bootstrappers into a sub directory to not break stuff?

Yes, that was my thinking, yes.  Rather not change too much at the minute, and only "add" new stuff.

Do you think we should move others into a sub folder as well?

**Comment by pascalberger** [comment]
> @gep13 said...
> Yes, that was my thinking, yes. Rather not change too much at the minute, and only "add" new stuff.
> 
> Do you think we should move others into a sub folder as well?

I would prefer to have everything in sub-folders, which would make using the repo much more intuitive. The question is what we will break with this? Official documentation uses redirects which we can change. Do we have tools (VS / VS Code extension, etc) which use the files directly?

**Comment by gep13** [comment]
If there are anything that uses them, it should be using the official download URL, i.e:

```
https://cakebuild.net/download/bootstrapper/powershell
```

So as long as we update the redirects, then we should be fine.  I can update this PR to move into a sub folder, and we can simply not merge it, until I am finished the PR to update the redirects on the website.

**Review by pascalberger — APPROVED** [review]
LGTM

**Comment by hlovdal** [comment]
Speaking of "to not break stuff", thousands of developers will have script files that on the third or fifth line states

```shell
# This file was downloaded from https://github.com/cake-build/resources
```

but when they go there now to check for potential updates, both `build.ps1` and `build.sh` are gone from the root folder where they used to be, and there exists no hint that they need to look in the `dotnet-framework` folder to find them.

The readme file really ought to be updated to reflect this.

**Comment by gep13** [comment]
@hlovdal I think that this is a great idea!  Would you be interested in doing a PR to update the README?

**Pull request merged**
