### PR TITLE
Use cake.config

### PR DESCRIPTION
**Pull request by flcdrg**
Parse cake.config (if it exists) to override the TOOLS default directory.

Implemented for both PowerShell and Bash. 

I'm no Bash expert, but it seems to "work on my machine" :-)

### CODE REVIEW

**Comment by gep13** [comment]
@cake-build/team what were your collective thoughts on this one?

**Comment by flcdrg** [comment]
Rebased against latest version and reverted line ending changes

**Comment by gep13** [comment]
@flcdrg just to keep you up to speed with this...

This isn't being ignored, but we are debating about whether we want to add this "extra" complexity into the bootstrapper, which is already pretty busy.

There is discussion about whether some of this logic should be brought into the Cake.exe directly, or perhaps a Cake.bootstrapper.exe, similar to what Paket does.

**Comment by flcdrg** [comment]
No worries. I updated it today after having a look at the cake chocolatey module.

As long as there's a way to use an alternative to the Tools folder, as our projects already use that.

Dave

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gep13** [comment]
>@flcdrg said...
after having a look at the cake chocolatey module.

What were your thoughts on it?

**Comment by flcdrg** [comment]
It worked, but I decided not to use it as it is slow for chocolatey to realise I already have nodejs installed, plus you get the UAC prompt which is jarring.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pascalberger** [comment]
We did some maintenance work on this repo which included removing of the `develop` branch which closed this PR.

@flcdrg As mentioned in a previous comment it's unlikely that we'll add much more complexity into existing bootstrappers, especially since in the meantime [Cake .NET Tool](https://cakebuild.net/docs/running-builds/runners/dotnet-core-tool) has been made the recommended approach. If you feel this is still an issue, please [start a discussion](https://github.com/cake-build/cake/discussions/category_choices).

**Comment by pascalberger** [comment]
Blog post is now available here: https://develop.cakebuild.net/blog/2020/12/config-bootstrap

**Pull request closed without merging**
