### PR TITLE
Add dotnet core only bootstrap pwsh file

### PR DESCRIPTION
**Pull request by makaanneo**
### dotnet core bootstrap pwsh ps1
This is my first pull request
I add a dotnet core only bootstrap to use cake build core.
### Summary
The new build_core.ps1 uses a dotnet console project to download the dependencies from nuget (to use dotnet cli only)
The new powershell file will be tested as well by using the powershell test pester test and will be executed by using Travis and AppVeyor

#### Windows
It works with pwsh 6 and powershell 5, dotnet 2.2
#### Linux
It works with pwsh 6 on linux, dotnet 2.2.203

### Tests
I added some pester tests to test the powershell file and as well modified the Travis CI and AppVeyorfile.

### Todos
May be some changes to documentation are needed and some addins may not work with pwsh or dotnet core

### CODE REVIEW

**Comment by devlead** [comment]
@makaanneo thanks for submitting this, we're not 100% sure on which direction the .NET Core boostrapper will head, it might be that we prefer to use the Cake.Tool in this case. So the @cake-build/cake-team / community needs to discuss way forward a bit more.

That said I really like what you've done with Travis/AppVeyor and the pester bits, much nicer than the thrown together hacky appveyor yml bits I've done.

PR #70 just made the old bootstrapper also work on PowerShell core.

Could you possibly do a separate PR that brings in pester tests for Travis & AppVeyor for the existing build.ps1?
(so they use same tests xplat, except PowerShell V2 which for obvious reasons will only run on windows)

This PR could then be rebased,more focused and build upon that work.

**Comment by makaanneo** [comment]
@devlead thanks for your Feedback. I will take a look in the Cake.Tool thing May it will give me some ideas on cake Build and dotnet core without mono (some kind of problem to solve for me).

I will do a seperate PR for the Integration Tests with pester Tests and the CI-Tools

**Comment by devlead** [comment]
@makaanneo excellent 👍 

FYI Cake's own repo bootstrapper uses Cake.Tool, probably needs some polish but works:
https://github.com/cake-build/cake/blob/develop/build.ps1

**Comment by makaanneo** [comment]
#71 created

**Pull request closed without merging**
