### PR TITLE
Use SystemProxy in WebClient

### PR DESCRIPTION
**Pull request by aateeque**
This enables executing the powershell script behind corporate proxy for example

### CODE REVIEW

**Comment by aateeque** [comment]
This was initially opened in the cake-build/cake#1765

**Comment by gep13** [comment]
@aateeque would an equivalent change also be required in the build.sh file?

**Comment by aateeque** [comment]
Don't think so; typically on Linux proxy would be handled by cntlm & `http_proxy`/`https_proxy` variables

**Comment by gep13** [comment]
@devlead can I get your thoughts on this?

**Pull request merged**
