### PR TITLE
Added Paths Configuration

### PR DESCRIPTION
**Pull request by gep13**
Relates to #3

### CODE REVIEW

**Comment by gep13** [comment]
@patriksvensson can you cast your eyes over this?

**Comment by patriksvensson** [comment]
I'm on my phone so can't comment on the individual lines, but I think it should be `./tools` and `./tools/Addins`.

**Comment by gep13** [comment]
>@patriksvensson said....
I'm on my phone so can't comment on the individual lines, but I think it should be ./tools and ./tools/Addins.

Do they need to be surrounded in `"` of `'`?

**Comment by patriksvensson** [comment]
No, that isn't necessary.

**Comment by patriksvensson** [comment]
Actually, I just realized things might break if we do. I should take a look at that asap.

**Comment by gep13** [comment]
@patriksvensson okay, let me know if you need me to check anything. I have updated this PR with your suggestion.

**Comment by patriksvensson** [comment]
@gep13 Looks good to me! Will merge.

**Pull request merged**
