### PR TITLE
This is handy

### PR DESCRIPTION
**Pull request by Jesse-Hufstetler**
I moved it from the depreciated https://github.com/cake-build/bootstrapper/blob/develop/res/scripts/build.cake

### CODE REVIEW

**Comment by gep13** [comment]
@Jesse-Hufstetler can you help me understand why you think that this is required?  Thanks.

**Comment by Jesse-Hufstetler** [comment]
I was setting up my first build with cake the other day and was trying to follow the instructions on the site, but couldn't find a starter build script anywhere. I knew when I ran the PowerShell commands in the tutorial at https://github.com/marcosnz/Cake-Example my stuff magically built and I wanted to know why that was. It turns out it used the script I'm asking to add, but that script was in the depreciated repository at https://github.com/cake-build/bootstrapper in some sort of res folder (I'm assuming res stands for resources). The readme file for that repository says THIS is the repository to replace the bootstrapper repository. Since this file seems to be able to build many .NET projects as-is I think it deserves to live in the new resources repository so beginners know the code is safe to use (and to be honest it seems like a good recommended starter build.cake for most people).

**Comment by gep13** [comment]
@Jesse-Hufstetler hmmm, I am not sure on this one, but I will definitely take it under consideration.  What do you use to edit your build scripts?  Have you seen the VSCode extension for Cake?  It contains the creation of a sample build script that you could get started with.  You can access this through the command palette and typing cake, and then selecting the sample build.cake command.  There is also a code snippet that you can use via typing cake within your cake script and selecting the appropriate one.

**Comment by agc93** [comment]
This seems like a bit of a step further than we've previously done with regards to templates for build scripts. Certainly none of the editors generate anything with pre-defined tasks like this.

Just personally this feels a bit, I guess opinionated? (again just IMHO)

**Comment by patriksvensson** [comment]
@agc93 Yeah, you’re actually right about that. Perhaps we should take a round of discussions what we would want from a template build script. A single ”Default” target and popularing args?

**Comment by agc93** [comment]
@patriksvensson [Here](https://github.com/cake-build/pantry/blob/master/template/build.cake.hbs) is the file I originally did for `cake-yeoman` that I've been using for tools since. Thoughts?

**Comment by gep13** [comment]
The output from the command in VSCode is currently:

```
///////////////////////////////////////////////////////////////////////////////
// ARGUMENTS
///////////////////////////////////////////////////////////////////////////////

var target = Argument("target", "Default");
var configuration = Argument("configuration", "Release");

///////////////////////////////////////////////////////////////////////////////
// SETUP / TEARDOWN
///////////////////////////////////////////////////////////////////////////////

Setup(ctx =>
{
   // Executed BEFORE the first task.
   Information("Running tasks...");
});

Teardown(ctx =>
{
   // Executed AFTER the last task.
   Information("Finished running tasks.");
});

///////////////////////////////////////////////////////////////////////////////
// TASKS
///////////////////////////////////////////////////////////////////////////////

Task("Default")
.Does(() => {
   Information("Hello Cake!");
});

RunTarget(target);
```

Which is very similar to what @agc93 has shown.  There are a couple things that I think should be added to this sample script.  The first is the TaskSetup and TaskTeardown, to show where those things can be used.  The second is at least one other Task, perhaps with a criteria, that would show how you can link to Tasks together.

Aside from those changes, I would agree that adding anything other then Information statements within the Tasks would be too much.

**Comment by agc93** [comment]
This is getting into contentious territory, but I'm not sure I agree about `TaskTeardown` and `TaskSetup` @gep13 . Personally, I always looked at the tool-generated Cake files as being minimum-viable scripts and I think *most* users aren't going to need it. (There's only [8 users on GitHub using it today](https://github.com/search?l=C%23&p=2&q=TaskTeardown+extension%3Acake+language%3AC%23+language%3AC%23&ref=advsearch&type=Code&utf8=%E2%9C%93))

Definitely agree with respect to adding a task with a dependency though.

**Comment by motowilliams** [comment]
I ran into this very scenario as @Jesse-Hufstetler . I'm working on some iteration zero scripts where Cake is an option for the user to select as the task runner. Having a simple yet Works In Most Scenarios™ sample file is useful to me. To get a sample, working starter build script I don't have in interact with task runner / build tools API or cobble together some string concatenation cruft to get a working build script. I can just make a HTTP request to a well known Uri and the user is set on a productive trajectory. Something that looks recursively for a sln file and maybe test projects seems like a good jumping off point for me.

**Comment by pascalberger** [comment]
We did some maintenance work on this repo which included removing of the `develop` branch which closed this PR.

In the meantime we have updated our website and it contains a [Getting started section](https://cakebuild.net/docs/getting-started/setting-up-a-new-project) containing a sample build script. Feel free to [get in touch](https://cakebuild.net/community/discuss) if you feel there's still anything missing.

**Pull request closed without merging**
