### PR TITLE
GH59: Added correct TLS version

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
Fixes #59

**Comment by gep13** [comment]
@devlead hmm, looks like PowerShell Version 2 doesn't like this 😢

**Comment by gep13** [comment]
@mholo65 I think I am right in saying that this will be needed for any request against GitHub, i.e. the packages.config, cake.config, etc.

**Comment by mholo65** [comment]
Ah, yes! How come we haven’t seen this issue before, until recently with downloading `dotnet-install.ps1`? GH enforced TLS1.2 back in February 2018..?!

**Comment by devlead** [comment]
> @devlead hmm, looks like PowerShell Version 2 doesn't like this 😢 

Ah it's running .NET 2.x I guess... perhaps time to drop 2 support or check if type exist/is null/ps version.

**Comment by devlead** [comment]
@mholo65 could be because the redirect via cloudflare.

**Comment by gep13** [comment]
@mholo65 I "think" we get away with it, due to our higher .Net Framework requirement, but I don't think there is any problem with being explicit.

>@devlead said...
Ah it's running .NET 2.x I guess... perhaps time to drop 2 support or check if type exist/is null/ps version.

I changed the logic slightly to do similar to how Chocolatey does it, and the build works again :-D

**Comment by mholo65** [comment]
> could be because the redirect via cloudflare.

Makes sense!

**Pull request closed without merging**
